
package ru.curs.showcase.test.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExternalWebServicesService", targetNamespace = "http://server.app.showcase.curs.ru/", wsdlLocation = "http://localhost/Showcase/forall/webservices?wsdl")
public class ExternalWebServicesService
    extends Service
{

    private final static URL EXTERNALWEBSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXTERNALWEBSERVICESSERVICE_EXCEPTION;
    private final static QName EXTERNALWEBSERVICESSERVICE_QNAME = new QName("http://server.app.showcase.curs.ru/", "ExternalWebServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/Showcase/forall/webservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXTERNALWEBSERVICESSERVICE_WSDL_LOCATION = url;
        EXTERNALWEBSERVICESSERVICE_EXCEPTION = e;
    }

    public ExternalWebServicesService() {
        super(__getWsdlLocation(), EXTERNALWEBSERVICESSERVICE_QNAME);
    }

    public ExternalWebServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXTERNALWEBSERVICESSERVICE_QNAME, features);
    }

    public ExternalWebServicesService(URL wsdlLocation) {
        super(wsdlLocation, EXTERNALWEBSERVICESSERVICE_QNAME);
    }

    public ExternalWebServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXTERNALWEBSERVICESSERVICE_QNAME, features);
    }

    public ExternalWebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalWebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShowcaseExternals
     */
    @WebEndpoint(name = "ShowcaseExternalsPort")
    public ShowcaseExternals getShowcaseExternalsPort() {
        return super.getPort(new QName("http://server.app.showcase.curs.ru/", "ShowcaseExternalsPort"), ShowcaseExternals.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShowcaseExternals
     */
    @WebEndpoint(name = "ShowcaseExternalsPort")
    public ShowcaseExternals getShowcaseExternalsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.app.showcase.curs.ru/", "ShowcaseExternalsPort"), ShowcaseExternals.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXTERNALWEBSERVICESSERVICE_EXCEPTION!= null) {
            throw EXTERNALWEBSERVICESSERVICE_EXCEPTION;
        }
        return EXTERNALWEBSERVICESSERVICE_WSDL_LOCATION;
    }

}
