
package ru.curs.showcase.test.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShowcaseExternals", targetNamespace = "http://showcase.curs.ru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShowcaseExternals {


    /**
     * 
     * @param procName
     * @param request
     * @return
     *     returns java.lang.String
     * @throws ShowcaseExportException_Exception
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "handle", targetNamespace = "http://showcase.curs.ru", className = "ru.curs.showcase.test.ws.Handle")
    @ResponseWrapper(localName = "handleResponse", targetNamespace = "http://showcase.curs.ru", className = "ru.curs.showcase.test.ws.HandleResponse")
    @Action(input = "http://showcase.curs.ru/ShowcaseExternals/handleRequest", output = "http://showcase.curs.ru/ShowcaseExternals/handleResponse", fault = {
        @FaultAction(className = ShowcaseExportException_Exception.class, value = "http://showcase.curs.ru/ShowcaseExternals/handle/Fault/ShowcaseExportException")
    })
    public String handle(
        @WebParam(name = "request", targetNamespace = "")
        String request,
        @WebParam(name = "procName", targetNamespace = "")
        String procName)
        throws ShowcaseExportException_Exception
    ;

    /**
     * 
     * @param procName
     * @param requestAnyXML
     * @return
     *     returns ru.curs.showcase.test.ws.ResponseAnyXML
     * @throws ShowcaseExportException_Exception
     */
    @WebMethod
    @WebResult(name = "responseAnyXML", targetNamespace = "http://showcase.curs.ru", partName = "responseAnyXML")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://showcase.curs.ru/ShowcaseExternals/handleXMLRequest", output = "http://showcase.curs.ru/ShowcaseExternals/handleXMLResponse", fault = {
        @FaultAction(className = ShowcaseExportException_Exception.class, value = "http://showcase.curs.ru/ShowcaseExternals/handleXML/Fault/ShowcaseExportException")
    })
    public ResponseAnyXML handleXML(
        @WebParam(name = "requestAnyXML", targetNamespace = "http://showcase.curs.ru", partName = "requestAnyXML")
        RequestAnyXML requestAnyXML,
        @WebParam(name = "procName", targetNamespace = "http://showcase.curs.ru", header = true, partName = "procName")
        String procName)
        throws ShowcaseExportException_Exception
    ;

}
