package ru.curs.showcase.test.ws;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebFault(name = "ShowcaseExportException", targetNamespace = "http://showcase.curs.ru")
public class ShowcaseExportException_Exception extends Exception {

	private static final long serialVersionUID = 7562181886054422201L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private final ShowcaseExportException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public ShowcaseExportException_Exception(String message, ShowcaseExportException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public ShowcaseExportException_Exception(String message, ShowcaseExportException faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         ru.curs.showcase.test.ws.ShowcaseExportException
	 */
	public ShowcaseExportException getFaultInfo() {
		return faultInfo;
	}

}
